// Monk writes MONK.md at the root of the connected folder on every save (see storage.js). It's
// a static schema/layout reference — an agent working in the repo reads it and then knows how
// to read and write Monk's files correctly (the id spaces, the pointer-vs-record rule, the
// derived-connections trick) instead of guessing from the file shapes.
//
// This constant is the file's entire content. It describes the *format*, not the current
// contents, so it never goes stale as long as it's kept in step with markdown.js / storage.js.
export const MONK_SCHEMA_DOC = `<!-- Auto-generated by Monk on every save. Safe to commit. Do not hand-edit — changes are overwritten. -->

# Monk workspace

This folder is a [Monk](https://monk.local) workspace: product research and specs, stored as
plain markdown so any tool — including an LLM agent — can read and write it directly. This file
documents the layout and file formats so those reads and writes stay valid.

Monk loads the whole folder when it connects and re-writes what changed (debounced ~700ms). It
also watches the folder: a file you write is picked up about a second after writing stops, so
write whole files rather than streaming into one. Monk never overwrites a file that changed since
it last read it — your version stays on disk and the app reports the divergence.

## Writing text

Don't hard-wrap. Write every paragraph and every list item on a single line, however long, and let
the reader wrap it. Monk shows text exactly as it is in the file, so a line broken at 72 columns
shows up as a ragged line in the app. In list sections (below) a wrapped continuation line is
joined back onto its item when Monk reads the file, and written back as one line on the next save;
prose isn't rejoined.

## Frontmatter format

Every file with metadata starts with a **single line of JSON** between \`---\` fences, then the
body:

\`\`\`
---
{"id":"...","title":"...","createdAt":"2026-01-01T00:00:00.000Z","updatedAt":"..."}
---
Body text goes here.
\`\`\`

It is JSON, not YAML. Timestamps in files are ISO strings. \`createdAt\`/\`updatedAt\` are on
every record; set \`updatedAt\` to now when you change something.

## Id conventions

- **Global records** (sections, documents, specs, signals, insights, activities, initiatives,
  boards) use a UUID (\`crypto.randomUUID()\`). Generate a fresh one; never reuse or collide.
- **Board cards** (actions, results) and **connections** use integers. If you add one, use an
  integer not taken by another card or connection **on the same board** — one higher than the
  largest on that board is always safe. Monk re-counts every board when it reads the folder, so
  the ids it hands out itself never collide with yours.
- The two fixed sections use literal ids, not UUIDs: \`product-knowledge\` and \`standards\`.

## Folder layout

\`\`\`
<workspace root>/
  MONK.md                     ← this file

  <section-uuid>/             ← a Sidebar section (folder marker: section.md)
    section.md                  { id, name, createdAt, updatedAt }, no body
    <doc-uuid>.md              a document: { id, title, createdAt, updatedAt } + markdown body

  product-knowledge/          ← fixed section: shared product context
  standards/                  ← fixed section: contracts agents build to (design system, a11y…)
                                (both are ordinary sections with a literal id; docs inside them
                                 feed a spec's "Start build" brief)

  <spec-uuid>/               ← a spec (folder marker: spec.md)
    spec.md                     see "Spec" below
    solution.md                 markdown in fixed ## sections, NO frontmatter (the Solution tab)
    plan.md                     plain markdown, NO frontmatter (the Plan tab)
    board/                      the Discovery board
      board.md                  { id, createdAt, updatedAt }, no body
      signals/<signal-uuid>.md  POINTER, see "Board cards" below
      insights/<insight-uuid>.md POINTER
      actions/<int>.md          local card
      results/<int>.md          local card

  DESIGN.md                   ← optional: this product's design system (see below)
  signals/<uuid>.md           ← global signal (see "Signal")
  insights/<uuid>.md          ← global insight (see "Insight")
  activities/<uuid>.md        ← global activity (see "Activity")
  initiatives/<uuid>.md       ← global initiative (see "Initiative")
\`\`\`

Any top-level folder without a \`section.md\` or \`spec.md\` marker (and not one of the reserved
names above) is ignored by Monk and never touched — a Monk workspace can live inside a larger
repo.

## Record formats

### Spec — \`<spec-uuid>/spec.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"draft|active|shipped","owner":"...",
 "initiativeId":"<initiative-uuid> | null",
 "openQuestions":[{"text":"...","checked":false,"resolution":"..."}],
 "acceptanceCriteria":[{"text":"...","checked":false}],
 "createdAt":"...","updatedAt":"..."}
---
## Problem

...

## Goals

...

## Non-goals

...
\`\`\`

- **Open questions**: \`text\` is the question and only the question. When one is answered, put the
  answer (and why) in \`resolution\` and set \`checked\` to \`true\`. \`resolution\` is optional —
  leave it out until there is one. The build brief lists unresolved questions as a stop condition
  and resolved ones with their answers.
- **Acceptance criteria**: one testable statement each. The reasoning behind a criterion belongs in
  \`solution.md\` Decisions, not in the criterion.
- **Status**: \`draft\` while the spec is being written, \`active\` once it's being built. An agent
  doesn't set \`shipped\`: when the build is done and every criterion is checked, say so in
  \`solution.md\` Notes and leave the status for a person to confirm.
- **Other sections**: text before the first heading, and any \`##\` section other than Problem,
  Goals and Non-goals, is kept as written below Non-goals and goes into the build brief. The app
  doesn't show it.

\`solution.md\` and \`plan.md\` are sibling files, no frontmatter. \`initiativeId\` links up to
\`initiatives/<id>.md\` (or \`null\`). \`plan.md\` holds the spec's tasks and approach (see "Plan"). \`design.md\` is the feature's
design intent (not visual language — that belongs in Standards), in any of these \`##\` sections,
in this order, each omitted when empty — one item per line (see "Writing text"):

\`\`\`
## Solution               freeform markdown — what is being built
## Design principles      1. text
## Constraints            - text
## Decisions              - text
## Artefacts              - [Title](url)
## Notes                  freeform markdown
\`\`\`

Text before the first heading, or under any other \`##\` heading, is kept as Notes — which is also
where sections Monk has since dropped end up, heading and all, rather than being discarded:
\`## Use cases\` and \`## Edge cases\` (both retired), and \`## Experience qualities\`. Renamed
sections keep parsing under their old heading — \`## Principles\` is read as Design principles.
Older specs tagged an artefact after an em dash with its kind and how closely to follow it
(\`— prototype, match exactly\`); neither is stored any more, and both are ignored on read.
Older specs also called this file \`design.md\`; it is still read under that name and
rewritten as \`solution.md\` on the next save.

### Plan — \`<spec-uuid>/plan.md\`

No frontmatter. The work as a task list, then the approach as freeform markdown:

\`\`\`
## Tasks

- [ ] A task that hasn't started
- [~] A task in progress
- [x] A finished task
- [!] A blocked task

## Approach

Freeform markdown.
\`\`\`

- Markers: \`[ ]\` to do, \`[~]\` in progress, \`[x]\` done, \`[!]\` blocked. One line per task — a task is
  its text and its state, nothing under it. Tasks stay in the order they were planned; changing a
  state never moves one. Unblocking a task returns it to to do.
- A plan.md without a \`## Tasks\` section is all approach, and is read and written back unchanged.
- Working through a plan: add the tasks before you build. Set \`[~]\` when you start one and \`[x]\`
  when it's done; record what was built and how it was checked in \`solution.md\` Notes. When you're
  stuck, set \`[!]\` and add an open question to \`spec.md\` saying what's in the way — the build
  brief lists both as stop conditions. Finishing every task doesn't make the spec \`shipped\`; a
  person decides that.

### Design system — \`DESIGN.md\` (optional, workspace root)

The visual language for everything built here: design tokens as YAML front matter, then the
reasoning as prose, in the format at <https://github.com/google-labs-code/design.md> — \`##\`
sections in the order Overview, Colors, Typography, Layout, Elevation & Depth, Shapes,
Components, Do's and Don'ts, any of which may be omitted.

Monk creates this file only when asked (the Design system entry in its sidebar), and then only
as a skeleton — \`version\`, \`name\` and every section heading, no values chosen — because a
visual language is decided, not generated. Its editor writes tokens and sections back in this
same format, keeping front-matter keys and sections it doesn't model; it does not keep YAML
comments.

To keep the file editable there, write the front matter as plain \`key: value\` lines nested at
most three deep (group → token → property), with single-line values — no \`|\` or \`>\` block
values, no lists or anchors inside \`colors\`, \`typography\`, \`rounded\`, \`spacing\` or
\`components\`, no tabs. A file outside that still works everywhere else; Monk just opens it as
raw Markdown and says why.

A minimal file in that shape:

\`\`\`
---
version: alpha
name: My Product
colors:
  ink: "#1A1C1E"
  accent: "#E3A44C"
typography:
  body:
    fontFamily: Inter
    fontSize: 15px
    lineHeight: 1.45
rounded:
  md: 5px
spacing:
  md: 16px
components:
  button-primary:
    backgroundColor: "{colors.accent}"
    textColor: "{colors.ink}"
    typography: "{typography.body}"
    rounded: "{rounded.md}"
    padding: "{spacing.md}"
---

## Overview

What the product should feel like, one paragraph per line.

## Colors

Why each color exists and what it means.

## Do's and Don'ts

- Do read every color from its token.
- Don't add a drop shadow to an ordinary card.
\`\`\`

Quote any value that starts with \`#\` or \`{\`. A component property is either a literal value or a
\`{group.token}\` reference to a token defined above. The properties a component may have are
\`backgroundColor\`, \`textColor\`, \`typography\`, \`rounded\`, \`padding\`, \`size\`, \`height\` and
\`width\`; a variant (hover, pressed) is its own component with a related name, such as
\`button-primary-hover\`. Under Do's and Don'ts each rule is one \`- Do …\` or \`- Don't …\` line;
anything else there is kept as notes.

However it gets written, every spec's build brief carries it as a contract, above the spec
itself, because it is true of everything in the product rather than of one feature. The brief
leaves out comments and any section with nothing written under it, so an unfilled skeleton
contributes nothing.

### Board cards — \`<spec-uuid>/board/<kind>/<id>.md\`

The board's connections are **not stored as files**. Each card lists its outgoing edges in a
\`connectsTo\` array in its own frontmatter; Monk rebuilds the flat connection list from those on
load. A connection's \`from\`/\`to\` are node ids on that board (a signal/insight node id is its
global UUID; an action/result node id is its integer).

- **signals/** and **insights/** entries are **pointers**, not copies:
  \`\`\`
  ---
  {"id":"<global signal or insight uuid>","connectsTo":["<node id>", 1042]}
  ---
  \`\`\`
  No body. The actual text lives in \`signals/<id>.md\` / \`insights/<id>.md\`. Editing the global
  record changes it on every board it's linked into.
- **actions/** entries:
  \`\`\`
  ---
  {"id":<int>,"connectsTo":[...],"ref":null}
  ---
  ## If we

  ...

  ## Then

  ...

  ## Expected

  ...
  \`\`\`
- **results/** entries: same frontmatter shape; body is plain text.
- \`ref\` (actions/results only): normally \`null\`. If set to \`{"boardId":"<spec-uuid>","itemId":<int>}\`
  the card is a live reference to a card on another spec's board and its own body is empty.

### Signal — \`signals/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>",
 "source": null,                              // or {"type":"activity","activityId":"<activity-uuid>"}
 "date":"<ISO>","link":"...","author":"...",
 "createdAt":"...","updatedAt":"..."}
---
The observation itself, as free text.
\`\`\`

\`source\` is either \`null\` (not tied to research) or an activity reference. There is no
free-text source.

### Insight — \`insights/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","sources":["<signal-uuid>", "..."],"createdAt":"...","updatedAt":"..."}
---
The insight, as free text.
\`\`\`

\`sources\` are the signal ids it was formed from.

### Activity — \`activities/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","name":"...","method":"Interview|Survey|Usage metrics|Client call|Codebase review|Other",
 "link":"...","date":"<ISO>","author":"...","createdAt":"...","updatedAt":"..."}
---
\`\`\`

No body. "Signals from this activity" is derived (any signal whose \`source.activityId\` matches).

\`Codebase review\` is research done by reading the product's code or docs — usually how an agent
researches. What goes where:

- A finding about the **product or the people using it** — a behaviour, a gap, something users
  can't do — is a signal, with that activity as its source. Signals are what a spec's Discovery
  board links to, and what insights are formed from.
- A fact about **how the code is built** — which function to reuse, where a pattern lives, what a
  change would break — is implementation grounding. It goes in the spec's \`solution.md\` Notes.

### Initiative — \`initiatives/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"active|paused|done",
 "openQuestions":[{"text":"...","checked":false,"resolution":"..."}],"createdAt":"...","updatedAt":"..."}
---
Freeform description — shared context for every spec under this initiative.
\`\`\`

"Specs in this initiative" is derived (any spec whose \`initiativeId\` matches). An initiative is
an epic; its specs are the tickets. \`openQuestions\` are the questions that span its specs; an
unchecked one is unresolved for every spec in the initiative. Answers go in \`resolution\`, the same
as on a spec. When a spec settles something the initiative's description still calls open, update
the description too.

### Section — \`<section-uuid>/section.md\`

\`\`\`
---
{"id":"<uuid>","name":"...","createdAt":"...","updatedAt":"..."}
---
\`\`\`

Documents are the other \`.md\` files in the same folder: \`{ id, title, createdAt, updatedAt }\`
frontmatter + markdown body.
`;
