// Monk writes MONK.md at the root of the connected folder on every save (see storage.js). It's
// a static schema/layout reference — an agent working in the repo reads it and then knows how
// to read and write Monk's files correctly (the id spaces, the pointer-vs-record rule, the
// derived-connections trick) instead of guessing from the file shapes.
//
// This constant is the file's entire content. It describes the *format*, not the current
// contents, so it never goes stale as long as it's kept in step with markdown.js / storage.js.
export const MONK_SCHEMA_DOC = `<!-- Auto-generated by Monk on every save. Safe to commit. Do not hand-edit — changes are overwritten. -->

# Monk workspace

This folder is a [Monk](https://monk.local) workspace: product research and specs, stored as
plain markdown so any tool — including an LLM agent — can read and write it directly. This file
documents the layout and file formats so those reads and writes stay valid.

Monk loads the whole folder when it connects and re-writes what changed (debounced ~700ms). It
does **not** watch for external edits yet, so after you change files here, reload Monk to see
them.

## Frontmatter format

Every file with metadata starts with a **single line of JSON** between \`---\` fences, then the
body:

\`\`\`
---
{"id":"...","title":"...","createdAt":"2026-01-01T00:00:00.000Z","updatedAt":"..."}
---
Body text goes here.
\`\`\`

It is JSON, not YAML. Timestamps in files are ISO strings. \`createdAt\`/\`updatedAt\` are on
every record; set \`updatedAt\` to now when you change something.

## Id conventions

- **Global records** (sections, documents, specs, signals, insights, activities, initiatives,
  boards) use a UUID (\`crypto.randomUUID()\`). Generate a fresh one; never reuse or collide.
- **Board cards** (actions, results) and **connections** use small integers from a
  workspace-wide counter. If you add one, pick an integer higher than every existing card and
  connection id in the workspace.
- The two fixed sections use literal ids, not UUIDs: \`product-knowledge\` and \`standards\`.

## Folder layout

\`\`\`
<workspace root>/
  MONK.md                     ← this file

  <section-uuid>/             ← a Sidebar section (folder marker: section.md)
    section.md                  { id, name, createdAt, updatedAt }, no body
    <doc-uuid>.md              a document: { id, title, createdAt, updatedAt } + markdown body

  product-knowledge/          ← fixed section: shared product context
  standards/                  ← fixed section: contracts agents build to (design system, a11y…)
                                (both are ordinary sections with a literal id; docs inside them
                                 feed a spec's "Start build" brief)

  <spec-uuid>/               ← a spec (folder marker: spec.md)
    spec.md                     see "Spec" below
    design.md                   markdown in fixed ## sections, NO frontmatter (the Design tab)
    flow.md                     use cases + flow map: JSON frontmatter, generated outline body
    plan.md                     plain markdown, NO frontmatter (the Plan tab)
    board/                      the Discovery board
      board.md                  { id, createdAt, updatedAt }, no body
      signals/<signal-uuid>.md  POINTER, see "Board cards" below
      insights/<insight-uuid>.md POINTER
      actions/<int>.md          local card
      results/<int>.md          local card

  signals/<uuid>.md           ← global signal (see "Signal")
  insights/<uuid>.md          ← global insight (see "Insight")
  activities/<uuid>.md        ← global activity (see "Activity")
  initiatives/<uuid>.md       ← global initiative (see "Initiative")
\`\`\`

Any top-level folder without a \`section.md\` or \`spec.md\` marker (and not one of the reserved
names above) is ignored by Monk and never touched — a Monk workspace can live inside a larger
repo.

## Record formats

### Spec — \`<spec-uuid>/spec.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"draft|active|shipped","owner":"...",
 "initiativeId":"<initiative-uuid> | null",
 "openQuestions":[{"text":"...","checked":false}],
 "acceptanceCriteria":[{"text":"...","checked":false}],
 "createdAt":"...","updatedAt":"..."}
---
## Problem

...

## Goals

...

## Non-goals

...
\`\`\`

\`design.md\` and \`plan.md\` are sibling files, no frontmatter. \`initiativeId\` links up to
\`initiatives/<id>.md\` (or \`null\`). \`plan.md\` is plain markdown. \`design.md\` is the feature's
design intent (not visual language — that belongs in Standards), in any of these \`##\` sections,
in this order, each omitted when empty — one item per line:

\`\`\`
## Principles             1. text
## Constraints            - text
## Edge cases             - when → then                     (then = _agent decides_ if left open)
## Decisions              - **Decision**
                              - Because: …   - Rejected: …     (each optional, nested)
## Artefacts              - [Title](url) — <link|prototype|design|diagram|persona>, <match exactly|follow direction|background>
## Notes                  freeform markdown
\`\`\`

Text before the first heading, or under any other \`##\` heading, is kept as Notes.

\`flow.md\` holds the spec's use cases and its flow map. The frontmatter is the data:

\`\`\`
{"useCases":[{"id","tier","text"}],"stages":[{"id","name"}],
 "steps":[{"id","useCase","stage","text"}],"links":[{"id","from","to","label"}]}
\`\`\`

\`tier\` is 0 = Primary, 1 = Secondary, 2 = Tertiary. Each use case is a row and each stage a
column; a step sits in one of each, and links go from step to step (a label is the branch
condition). The body is a readable outline of every path, regenerated on each save — edit the
frontmatter, not the outline. Older specs kept use cases in design.md's \`## Use cases\`; Monk moves
them here on load.

### Board cards — \`<spec-uuid>/board/<kind>/<id>.md\`

The board's connections are **not stored as files**. Each card lists its outgoing edges in a
\`connectsTo\` array in its own frontmatter; Monk rebuilds the flat connection list from those on
load. A connection's \`from\`/\`to\` are node ids on that board (a signal/insight node id is its
global UUID; an action/result node id is its integer).

- **signals/** and **insights/** entries are **pointers**, not copies:
  \`\`\`
  ---
  {"id":"<global signal or insight uuid>","connectsTo":["<node id>", 1042]}
  ---
  \`\`\`
  No body. The actual text lives in \`signals/<id>.md\` / \`insights/<id>.md\`. Editing the global
  record changes it on every board it's linked into.
- **actions/** entries:
  \`\`\`
  ---
  {"id":<int>,"connectsTo":[...],"ref":null}
  ---
  ## If we

  ...

  ## Then

  ...

  ## Expected

  ...
  \`\`\`
- **results/** entries: same frontmatter shape; body is plain text.
- \`ref\` (actions/results only): normally \`null\`. If set to \`{"boardId":"<spec-uuid>","itemId":<int>}\`
  the card is a live reference to a card on another spec's board and its own body is empty.

### Signal — \`signals/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>",
 "source": null,                              // or {"type":"activity","activityId":"<activity-uuid>"}
 "date":"<ISO>","link":"...","author":"...",
 "createdAt":"...","updatedAt":"..."}
---
The observation itself, as free text.
\`\`\`

\`source\` is either \`null\` (not tied to research) or an activity reference. There is no
free-text source.

### Insight — \`insights/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","sources":["<signal-uuid>", "..."],"createdAt":"...","updatedAt":"..."}
---
The insight, as free text.
\`\`\`

\`sources\` are the signal ids it was formed from.

### Activity — \`activities/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","name":"...","method":"Interview|Survey|Usage metrics|Client call|Other",
 "link":"...","date":"<ISO>","author":"...","createdAt":"...","updatedAt":"..."}
---
\`\`\`

No body. "Signals from this activity" is derived (any signal whose \`source.activityId\` matches).

### Initiative — \`initiatives/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"active|paused|done","createdAt":"...","updatedAt":"..."}
---
Freeform description — shared context for every spec under this initiative.
\`\`\`

"Specs in this initiative" is derived (any spec whose \`initiativeId\` matches). An initiative is
an epic; its specs are the tickets.

### Section — \`<section-uuid>/section.md\`

\`\`\`
---
{"id":"<uuid>","name":"...","createdAt":"...","updatedAt":"..."}
---
\`\`\`

Documents are the other \`.md\` files in the same folder: \`{ id, title, createdAt, updatedAt }\`
frontmatter + markdown body.
`;
