// Monk writes MONK.md at the root of the connected folder on every save (see storage.js). It's
// a static schema/layout reference — an agent working in the repo reads it and then knows how
// to read and write Monk's files correctly (the id spaces, the pointer-vs-record rule, the
// derived-connections trick) instead of guessing from the file shapes.
//
// This constant is the file's entire content. It describes the *format*, not the current
// contents, so it never goes stale as long as it's kept in step with markdown.js / storage.js.
export const MONK_SCHEMA_DOC = `<!-- Auto-generated by Monk on every save. Safe to commit. Do not hand-edit — changes are overwritten. -->

# Monk workspace

This folder is a [Monk](https://monk.local) workspace: product research and specs, stored as
plain markdown so any tool — including an LLM agent — can read and write it directly. This file
documents the layout and file formats so those reads and writes stay valid.

It covers where things go, not what to put in them: \`WRITING.md\`, beside this file, is what each
field is for and how much to write in it. Read that too before filling one in — the usual failure
is a well-formed file with three paragraphs where one sentence was the answer. Unlike this file it
belongs to the workspace: Monk writes it once and never again, the team edits it (in the app, or
here), and its rules are theirs. Follow it; don't rewrite it unless you were asked to.

Monk loads the whole folder when it connects and re-writes what changed (debounced ~700ms). It
also watches the folder: a file you write is picked up about a second after writing stops, so
write whole files rather than streaming into one. Monk never overwrites a file that changed since
it last read it — your version stays on disk and the app reports the divergence.

## Writing text

Don't hard-wrap. Write every paragraph and every list item on a single line, however long, and let
the reader wrap it. Monk shows text exactly as it is in the file, so a line broken at 72 columns
shows up as a ragged line in the app. In list sections (below) a wrapped continuation line is
joined back onto its item when Monk reads the file, and written back as one line on the next save;
prose isn't rejoined.

## Frontmatter format

Every file with metadata starts with a **single line of JSON** between \`---\` fences, then the
body:

\`\`\`
---
{"id":"...","title":"...","createdAt":"2026-01-01T00:00:00.000Z","updatedAt":"..."}
---
Body text goes here.
\`\`\`

It is JSON, not YAML. Timestamps in files are ISO strings. \`createdAt\`/\`updatedAt\` are on
every record; set \`updatedAt\` to now when you change something.

## Id conventions

- **Global records** (sections, documents, specs, signals, insights, initiatives, research plans,
  boards) use a UUID (\`crypto.randomUUID()\`). Generate a fresh one; never reuse or collide.
- **Board cards** (actions, results) and **connections** use integers. If you add one, use an
  integer not taken by another card or connection **on the same board** — one higher than the
  largest on that board is always safe. Monk re-counts every board when it reads the folder, so
  the ids it hands out itself never collide with yours.
- The two fixed sections use literal ids, not UUIDs: \`product-knowledge\` and \`standards\`.

## Folder layout

\`\`\`
<workspace root>/
  MONK.md                     ← this file: where everything goes
  WRITING.md                  ← how to write what goes in it (the workspace's own; see below)

  <section-uuid>/             ← a Sidebar section (folder marker: section.md)
    section.md                  { id, name, createdAt, updatedAt }, no body
    <doc-uuid>.md              a document: { id, title, createdAt, updatedAt } + markdown body

  product-knowledge/          ← fixed section: shared product context
  standards/                  ← fixed section: contracts agents build to (accessibility, house rules…)
                                (both are ordinary sections with a literal id; read both before
                                 building any spec)

  <spec-uuid>/               ← a spec (folder marker: spec.md)
    spec.md                     see "Spec" below
    solution.md                 markdown in fixed ## sections, NO frontmatter (the Solution tab)
    plan.md                     plain markdown, NO frontmatter (the Plan tab)
    sketches/<filename>         the spec's sketches, see "Solution" below (only once one exists)
    sources/<filename>          uploaded source files, see "Sources" below (only once one exists)

  DESIGN.md                   ← optional: this product's design system (see below)
  signals/<uuid>.md           ← global signal (see "Signal")
  insights/<uuid>.md          ← global insight (see "Insight")
  initiatives/<uuid>.md       ← global initiative (see "Initiative")
  initiatives/<uuid>/sources/<filename>   uploaded source files (only once one exists — an
                                            initiative otherwise has no folder of its own)
  research-plans/<uuid>.md    ← global research plan (see "Research plan")
  research-plans/<uuid>/
    board/                      the plan's board (its Analysis tab)
      board.md                  { id, createdAt, updatedAt }, no body; id is the plan's
      signals/<signal-uuid>.md  POINTER, see "Board cards" below
      insights/<insight-uuid>.md POINTER
      actions/<int>.md          local card
      results/<int>.md          local card
    sources/<filename>          uploaded source files, see "Sources" below (only once one exists)
  activities/                 ← legacy, don't write here (see "Legacy")
  _migrated-activities/       ← originals of migrated activities; Monk never reads it
\`\`\`

Any top-level folder without a \`section.md\` or \`spec.md\` marker (and not one of the reserved
names above) is ignored by Monk and never touched — a Monk workspace can live inside a larger
repo.

## Record formats

### Spec — \`<spec-uuid>/spec.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"draft|active|shipped","owner":"...",
 "initiativeId":"<initiative-uuid> | null",
 "researchPlanIds":["<research-plan-uuid>"],   // optional
 "sources":[{"kind":"document","sectionId":"...","docId":"..."},{"kind":"file","name":"..."}],  // optional
 "openQuestions":[{"text":"...","checked":false,"resolution":"..."}],
 "acceptanceCriteria":[{"text":"...","checked":false}],
 "createdAt":"...","updatedAt":"..."}
---
## Problem

...

## Goals

...

## Non-goals

...
\`\`\`

- **Non-goals** are binding: they fence the scope, so don't build past them.
- **Open questions**: \`text\` is the question and only the question. When one is answered, put the
  answer (and why) in \`resolution\` and set \`checked\` to \`true\`. \`resolution\` is optional —
  leave it out until there is one. An unchecked question is a stop condition: don't decide it
  silently while building — ask, or make a flagged assumption. A resolved one is settled; build to
  its answer.
- **Acceptance criteria**: one testable statement each. The reasoning behind a criterion belongs in
  \`solution.md\` Decisions, not in the criterion.
- **Status**: \`draft\` while the spec is being written, \`active\` once it's being built. An agent
  doesn't set \`shipped\`: when the build is done and every criterion is checked, say so in
  \`solution.md\` Notes and leave the status for a person to confirm.
- **Research plans**: \`researchPlanIds\` lists the research plans behind the spec, as pointers into
  \`research-plans/\`. Leave it out when there are none. A plan's own board can also point the other
  way, at a spec its Analysis led to — see "Board cards" above (\`results/\`) — and adding one there
  adds this field too, so either side finds the other.
- **Sources**: reference material behind the spec — see "Sources" below. Distinct from
  \`solution.md\`'s Artefacts (external links only): a source is something that lives in or under
  this workspace. Leave it out when there are none.
- **Other sections**: text before the first heading, and any \`##\` section other than Problem,
  Goals and Non-goals, is kept as written below Non-goals. The app doesn't show it.

\`solution.md\` and \`plan.md\` are sibling files, no frontmatter. \`initiativeId\` links up to
\`initiatives/<id>.md\` (or \`null\`). \`plan.md\` holds the spec's tasks and approach (see "Plan"). \`solution.md\` is the feature's
design intent (not visual language — that belongs in Standards), in any of these \`##\` sections,
in this order, each omitted when empty — one item per line (see "Writing text"):

\`\`\`
## Solution               freeform markdown — what to build; the sections below qualify it
## Sketches               - ![Caption](sketches/file) — the outcome it has to achieve
## Design principles      1. text — intent to optimise for; how to get there is your call
## Constraints            - text — binding; if one can't be met, stop and flag it
## Decisions              - text — settled; don't reverse one without flagging it
## Artefacts              - [Title](url) — reference material to consult
## Notes                  freeform markdown — background
\`\`\`

A **sketch** is a crude picture of one option, in \`<spec-uuid>/sketches/\`, with the outcome it has
to achieve after an em dash. Write it as an SVG in that folder and add its line: nothing needs the
app, and a text sketch diffs in review like every other file here. Two sketches whose outcome text
matches word for word are shown as one set of alternatives, so reuse the text exactly. The path is
read as written and only \`sketches/<filename>\` resolves — a sketch is rendered in an \`img\`, never
inlined, so script inside an SVG never runs. See \`WRITING.md\` for what makes a sketch worth
drawing. Distinct from an Artefact (a link to something outside the workspace) and from a Source
(reference material behind the spec, in \`sources/\`): a sketch is a proposal inside it.

Text before the first heading, or under any other \`##\` heading, is kept as Notes — which is also
where sections Monk has since dropped end up, heading and all, rather than being discarded:
\`## Use cases\` and \`## Edge cases\` (both retired), and \`## Experience qualities\`. Renamed
sections keep parsing under their old heading — \`## Principles\` is read as Design principles.
Older specs tagged an artefact after an em dash with its kind and how closely to follow it
(\`— prototype, match exactly\`); neither is stored any more, and both are ignored on read.
Older specs also called this file \`design.md\`; it is still read under that name and
rewritten as \`solution.md\` on the next save.

### Plan — \`<spec-uuid>/plan.md\`

No frontmatter. The work as a task list, then the approach as freeform markdown:

\`\`\`
## Tasks

- [ ] A task that hasn't started
- [~] A task in progress
- [x] A finished task
- [!] A blocked task

## Approach

Freeform markdown.
\`\`\`

- Markers: \`[ ]\` to do, \`[~]\` in progress, \`[x]\` done, \`[!]\` blocked. One line per task — a task is
  its text and its state, nothing under it. Tasks stay in the order they were planned; changing a
  state never moves one. Unblocking a task returns it to to do.
- A plan.md without a \`## Tasks\` section is all approach, and is read and written back unchanged.
- Working through a plan: add the tasks before you build. Set \`[~]\` when you start one and \`[x]\`
  when it's done; record what was built and how it was checked in \`solution.md\` Notes. When you're
  stuck, set \`[!]\` and add an open question to \`spec.md\` saying what's in the way — both are
  stop conditions. Finishing every task doesn't make the spec \`shipped\`; a person decides that.

### Design system — \`DESIGN.md\` (optional, workspace root)

The visual language for everything built here: design tokens as YAML front matter, then the
reasoning as prose, in the format at <https://github.com/google-labs-code/design.md> — \`##\`
sections in the order Overview, Colors, Typography, Layout, Elevation & Depth, Shapes,
Components, Do's and Don'ts, any of which may be omitted.

Monk creates this file only when asked (the Design system entry in its sidebar), and then only
as a skeleton — \`version\`, \`name\` and every section heading, no values chosen — because a
visual language is decided, not generated. Its editor writes tokens and sections back in this
same format, keeping front-matter keys and sections it doesn't model; it does not keep YAML
comments.

To keep the file editable there, write the front matter as plain \`key: value\` lines nested at
most three deep (group → token → property), with single-line values — no \`|\` or \`>\` block
values, no lists or anchors inside \`colors\`, \`typography\`, \`rounded\`, \`spacing\` or
\`components\`, no tabs. A file outside that still works everywhere else; Monk just opens it as
raw Markdown and says why.

A minimal file in that shape:

\`\`\`
---
version: alpha
name: My Product
colors:
  ink: "#1A1C1E"
  accent: "#E3A44C"
typography:
  body:
    fontFamily: Inter
    fontSize: 15px
    lineHeight: 1.45
rounded:
  md: 5px
  full: 50%
spacing:
  md: 16px
components:
  button-primary:
    backgroundColor: "{colors.accent}"
    textColor: "{colors.ink}"
    typography: "{typography.body}"
    rounded: "{rounded.md}"
    padding: "{spacing.md}"
---

## Overview

What the product should feel like, one paragraph per line.

## Colors

Why each color exists and what it means.

## Do's and Don'ts

- Do read every color from its token.
- Don't add a drop shadow to an ordinary card.
\`\`\`

Quote any value that starts with \`#\` or \`{\`. A radius is a length (\`px\`, \`em\`, \`rem\`) or a
percentage (\`50%\`). A component property is either a literal value or a
\`{group.token}\` reference to a token defined above. The properties a component may have are
\`backgroundColor\`, \`textColor\`, \`typography\`, \`rounded\`, \`padding\`, \`size\`, \`height\` and
\`width\`; a variant (hover, pressed) is its own component with a related name, such as
\`button-primary-hover\`. Under Do's and Don'ts each rule is one \`- Do …\` or \`- Don't …\` line;
anything else there is kept as notes.

However it gets written, it's a contract for everything built in the product, not just one
feature: use its tokens rather than inventing values, and where a component is specified, match
it. Comments, and sections with nothing written under them, carry no rules.

### Board cards — \`research-plans/<plan-uuid>/board/<kind>/<id>.md\`

A board belongs to a research plan: it's where the study's signals are collected, turned into
insights, and followed through to actions — and the specs those actions' results become.


The board's connections are **not stored as files**. Each card lists its outgoing edges in a
\`connectsTo\` array in its own frontmatter; Monk rebuilds the flat connection list from those on
load. A connection's \`from\`/\`to\` are node ids on that board (a signal/insight node id is its
global UUID; an action/result node id is its local integer).

- **signals/** and **insights/** entries are **pointers**, not copies:
  \`\`\`
  ---
  {"id":"<global signal or insight uuid>","connectsTo":["<node id>", 1042]}
  ---
  \`\`\`
  No body. The actual text lives in \`signals/<id>.md\` / \`insights/<id>.md\`. Editing the global
  record changes it on every board it's linked into.
- **results/** entries are pointers too, but to a spec rather than a research record:
  \`\`\`
  ---
  {"id":1042,"connectsTo":[],"specId":"<spec uuid> | null"}
  ---
  \`\`\`
  No body. \`id\` is this card's own local integer (what a connection's \`from\`/\`to\` uses);
  \`specId\` points at \`<spec-uuid>/spec.md\`. Linking or creating a spec here also adds this
  plan's id to that spec's own \`researchPlanIds\` (see "Spec"), so the two stay in sync.
- **actions/** entries:
  \`\`\`
  ---
  {"id":<int>,"connectsTo":[...],"ref":null}
  ---
  ## If we

  ...

  ## Then

  ...

  ## Expected

  ...
  \`\`\`
- \`ref\` (actions only): normally \`null\`. If set to \`{"boardId":"<plan-uuid>","itemId":<int>}\`
  the card is a live reference to an action on another research plan's board and its own body is empty.

### Signal — \`signals/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","date":"<ISO>","link":"...","author":"...",
 "createdAt":"...","updatedAt":"..."}
---
The observation itself, as free text.
\`\`\`

A signal belongs to a study by being linked onto that research plan's board — a pointer in
\`research-plans/<plan-uuid>/board/signals/\` (see "Board cards"). One signal can sit on several plans'
boards. \`date\` is when it was observed. Older signals may carry \`source\` or \`session\`; both are
ignored and dropped on the next save.

Research done by reading the product's code or docs — usually how an agent researches — goes the
same way. What goes where:

- A finding about the **product or the people using it** — a behaviour, a gap, something users
  can't do — is a signal, linked onto the board of the research plan it serves. With no such plan,
  use the plan titled "Codebase review" (create it if it doesn't exist, with "Codebase review" in
  its \`activities\`). Insights are formed from the signals on the same board.
- A fact about **how the code is built** — which function to reuse, where a pattern lives, what a
  change would break — is implementation grounding. It goes in the spec's \`solution.md\` Notes.

### Insight — \`insights/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","sources":["<signal-uuid>", "..."],"createdAt":"...","updatedAt":"..."}
---
The insight, as free text.
\`\`\`

\`sources\` are the signal ids it was formed from.


### Initiative — \`initiatives/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"active|paused|done",
 "outcomes":[{"text":"...","metric":"...","baseline":"...","target":"...","current":"..."}],   // optional
 "openQuestions":[{"text":"...","checked":false,"resolution":"..."}],
 "sources":[{"kind":"document","sectionId":"...","docId":"..."},{"kind":"file","name":"..."}],  // optional
 "createdAt":"...","updatedAt":"..."}
---
Freeform description — shared context for every spec under this initiative.
\`\`\`

\`outcomes\` are why the initiative exists: each is a measurable change in customer behaviour or
business value the work should produce. \`text\` states the change; \`metric\` is what's measured,
\`baseline\` → \`target\` where it starts and where it should get to, \`current\` the latest reading.
All are free-text strings (\`"20%"\`, \`"9/qtr"\`); only \`text\` is required. An outcome is not an
acceptance criterion — every spec can ship without it moving.

"Specs in this initiative" is derived (any spec whose \`initiativeId\` matches). An initiative is
an epic; its specs are the tickets. \`openQuestions\` are the questions that span its specs; an
unchecked one is unresolved for every spec in the initiative. Answers go in \`resolution\`, the same
as on a spec. When a spec settles something the initiative's description still calls open, update
the description too. \`sources\` is reference material behind the initiative — see "Sources" below.

### Research plan — \`research-plans/<uuid>.md\`

\`\`\`
---
{"id":"<uuid>","title":"...","status":"planned|fieldwork|synthesis|done",
 "initiativeId":"<initiative-uuid> | null",
 "researchQuestions":[{"text":"...","insightIds":["<insight-uuid>"]}],
 "activities":["Interview with P3","Survey wave 1"],   // optional
 "sources":[{"kind":"document","sectionId":"...","docId":"..."},{"kind":"file","name":"..."}],  // optional
 "createdAt":"...","updatedAt":"..."}
---
## Problem statement

...

## Background

...

## Approach

...

## Participants

...

## Discussion guide

...
\`\`\`

The study behind a set of signals: why the research is being done, how, with whom, and what it has
to find out. Each section is left out while it's empty.

- **Problem statement**: the decision or problem the research serves. **Background**: what is
  already known, and what prompted the study.
- **Approach**: the method, and why it fits. **Participants**: who takes part, and how they're
  recruited.
- **Research questions** are what the team needs to learn, not what gets asked. A question is
  answered when \`insightIds\` lists at least one insight that answers it; there is no checkbox. Link
  an insight only when it really answers the question.
- **Discussion guide**: what is asked or done in each session, in order — interview questions,
  survey items, tasks. It serves the research questions rather than repeating them.
- **Activities**: what was done for the study — "Interview with P3", "Survey wave 1" — one plain
  string each, with nothing else to them and no link to signals. Leave the key out when there are none.
- **Board** (\`research-plans/<uuid>/board/\`, the Analysis tab): the signals the study collected, the
  insights formed from them, and the actions and results they lead to — see "Board cards". Research
  questions are answered by insights, which are usually, but don't have to be, on this board.
- **Specs informed by this plan** are derived too: any spec whose \`researchPlanIds\` includes it.
- **Sources**: reference material behind the study — see "Sources" below. Leave it out when there
  are none.
- **Status**: \`planned\` before any activity, \`fieldwork\` while they run, \`synthesis\`
  while signals are being turned into insights, \`done\` when the questions are answered or dropped.
- Any other \`##\` section, and text before the first heading, is kept as written. The app doesn't
  show it.

### Sources — a spec's, initiative's or research plan's \`sources\` array

Reference material behind the record — distinct from a spec's \`solution.md\` Artefacts, which are
external links only. A source is one of two shapes:

\`\`\`
{"kind":"document","sectionId":"<section-uuid>","docId":"<doc-uuid>"}   // a pointer to a workspace document
{"kind":"file","name":"<filename>"}                                     // an uploaded file
\`\`\`

A \`document\` source points at a document already in the workspace — in a custom section, or in
Product Knowledge or Standards — the same document, not a copy; editing it changes it everywhere
it's linked. A \`file\` source is an uploaded file that lives in the record's own \`sources/\`
subfolder, next to its \`.md\` file (a spec's or research plan's; an initiative gets a \`sources/\`
folder only once a file is uploaded to it, since it's otherwise a flat file with none). \`name\` is
that file's name in \`sources/\` — read it, but don't hand-edit \`sources/\` directly: added or
removed files there aren't picked up unless \`sources\` in the frontmatter is updated to match.

### Legacy

**Activities — \`activities/<uuid>.md\`.** Older workspaces recorded research as activity files, with
signals pointing at them (\`"source":{"type":"activity","activityId":"..."}\`). Monk no longer writes
this folder; don't create files in it. When Monk finds one, it moves it into the current format and
keeps the original file in \`_migrated-activities/\`:

- An activity with a \`planId\` becomes a line in that plan's \`activities\`, and its signals are linked
  onto that plan's board.
- An activity without one becomes a research plan with the same id (its method becomes Approach),
  and its signals are linked onto that plan's board.
- \`source\` is dropped from every signal.

**Spec boards — \`<spec-uuid>/board/\`.** Specs used to have their own Discovery board. The board now
belongs to research plans, and Monk removes a spec's \`board/\` folder when it finds one. Don't write
there — link the spec to the research plan behind it instead (\`researchPlanIds\`).

### Section — \`<section-uuid>/section.md\`

\`\`\`
---
{"id":"<uuid>","name":"...","createdAt":"...","updatedAt":"..."}
---
\`\`\`

Documents are the other \`.md\` files in the same folder: \`{ id, title, createdAt, updatedAt }\`
frontmatter + markdown body.
`;
