// Monk writes WRITING.md at the root of the connected folder alongside MONK.md (see storage.js).
//
// The two are a pair and the split matters: MONK.md (monkSchema.js) says where a thing goes —
// file names, frontmatter, field names, how text is stored. This says what to write in it —
// what each field is for, how long it should be, and what a bad answer looks like. Left to
// itself an agent fills every field to the brim with plausible prose, which is expensive for
// the next reader and for the next agent's context; this is the countermeasure.
//
// It's a constant for the same reason MONK.md is: it describes the fields, not the workspace,
// so it never goes stale as long as it's kept in step with the app's own fields. Anything that
// is a *format* question belongs in MONK.md and is linked to rather than repeated here, so the
// two can't drift.
export const WRITING_GUIDE_DOC = `<!-- Auto-generated by Monk on every save. Safe to commit. Do not hand-edit — changes are overwritten. -->

# Writing guide for AI collaborators

You are co-writing research plans and specs with a product team. These files are read by busy humans and by other AI agents that will build from them. Every sentence costs both a reader's attention and an agent's context. Write the minimum that lets the reader act correctly.

This guide covers what to write. \`MONK.md\` covers where it goes: file names, frontmatter, field names, and how text is stored — in particular, never hard-wrap a paragraph or a list item. Read that before writing files directly.

## Global rules

1. **Blank beats filler.** If you don't know something, leave the field empty or ask one question. Never pad a field to make the document look complete.
2. **One field, one job.** Each field answers one question (see below). Don't answer another field's question in it, and don't repeat content across fields.
3. **Use the link fields.** Reference material goes in Sources, the research behind a spec in its research plans, an insight's evidence in its signals, an answer to a research question in the insight linked to it. A sentence pointing at something a link field already holds ("as the onboarding research showed…") is a missing link, not context.
4. **Specific over general.** Name the user, the situation, the number, the screen. Delete any sentence that would be true of any product ("users want a seamless experience").
5. **Mark what you invented.** Anything not grounded in the user's input or linked evidence gets an \`[assumption]\` tag — plain text; nothing parses it. The human decides whether it stays. If the build would actually turn on the answer, make it an open question instead.
6. **Match the field's shape.** Prose fields (Problem, Goals, Non-goals, Background, Solution, Description…) take plain prose, or a short bullet list where the field is a set of items. No headings inside a field, no bold, no preamble ("This section outlines…"), no closing summary. List fields (open questions, acceptance criteria, design principles, constraints, decisions, artefacts, outcomes, research questions, activities, tasks) take one item per line: the item is its text and nothing else — no sub-bullets, no explanation underneath.
7. **Respect the budget.** The budgets below are ceilings, not targets. Hitting the ceiling should be rare.
8. **Draft small, then offer.** When filling a template, draft the fields you have evidence for. List the ones you left empty and why in one line, in chat, not in the file. Offer to expand; don't expand by default.

Titles are names, not summaries: what the thing is, in a few words, distinguishable from its siblings.

Before saving, run one test: *Could I delete this sentence without the reader losing something they need?* If yes, delete it.

---

## Research plan

Research exists to serve a decision. Do just enough of it to make that decision with confidence, then stop.

**Problem statement.** *What decision will this research inform?*
Budget: 1–2 sentences. Name the decision and who makes it.
Done when: someone could say whether the research succeeded.
Avoid: describing a topic ("Understanding how users feel about onboarding").

> ✗ We want to gain a deeper understanding of our users' onboarding experience to identify opportunities for improvement.
> ✓ We need to decide whether to cut the setup wizard to one step before the Q4 redesign. We don't know which steps new admins actually need on day one.

**Background.** *What do we already know, and what triggered this?*
Budget: 2–4 sentences. Link existing Signals and Insights instead of summarising them.
Avoid: the product's history, or restating the problem.

**Approach.** *Which method, and why does it fit these questions?*
Budget: 2–3 sentences. The method must follow from the research questions. If the questions are about behaviour, don't propose a survey of opinions.
Avoid: listing several methods "to triangulate" without a reason each is needed.

**Participants.** *Who, how many, and how we'll find them.*
Budget: 1–3 sentences. Define people by behaviour or situation ("admins who set up an account in the last 30 days"), not by demographics. Small numbers are fine: 5–8 per segment for qualitative work.

**Research questions.** *What do we need to learn?* A list, 3–6 items.
These are questions for the team, not questions for participants. Each should be answerable by the study and should change the decision depending on its answer.
A question is answered by linking the insight that answers it — not by editing the question and not by ticking anything. Link an insight only if it really answers the question: a question with nothing linked is a visible gap in the evidence, which is the point.
Avoid: questions you'd ask a participant verbatim, and yes/no questions.

> ✗ Do users like the setup wizard?
> ✓ Which wizard steps do new admins complete, skip, or come back to later?

**Discussion guide.** *What will we ask or do in each session, in order?*
A numbered list. Ask about specific past behaviour ("Tell me about the last time you…"), not predictions ("Would you use…") or opinions ("Do you like…"). No leading questions. One question per item. Include timing only if the session is tight.

**Activities.** *What was actually done.* One plain line each — "Interview with P3", "Survey wave 1". No method notes, no dates, no findings: what was found is a signal on the board.

**Sources.** Reference material behind the study: workspace documents, or files uploaded to the plan. Links only, no descriptions.

### Analysis board

The board runs left to right: signals → insights → actions → the spec an action becomes. Keep the first three strictly separate. Most bad analysis comes from mixing observation and interpretation.

**Signal.** *What was observed?* One fact per card, 1–2 sentences. A quote or a behaviour. No interpretation, no "this suggests".
Attribution belongs in the card's own fields, not in the sentence: *date* when it was observed, *author* whose observation it is, *link* to the recording, transcript, ticket or dashboard. Name a participant in the text only when the fact is about them.

> ✗ Users find the permissions page confusing.
> ✓ P3 opened the permissions page twice and left both times without saving.

**Insight.** *What do these signals mean together?* One sentence, ideally with a "because". Link the signals it came from rather than quoting them. It must be non-obvious: if it restates one signal, it isn't an insight yet.

> ✓ Admins postpone permissions setup because they don't know their team's roles until after launch.

**Action.** *What will we try, and what do we expect?*
- *If we*: one concrete change.
- *Then*: the behaviour change we expect.
- *Expected*: a measurable result with a number or threshold, so the bet can fail.

Avoid: "improve", "optimise", "enhance" without a measure.

**Spec.** The last column links the spec an action becomes. Nothing to write here but the spec's title — the content goes in the spec itself.

---

## Initiative

**Description.** *What context must every spec in this initiative inherit?* Budget: 3–5 sentences: who it's for, why now, and the boundary of the initiative. Specs will link here instead of repeating this, so put shared context here once.

**Outcomes.** *What change in customer behaviour or business value will this cause, and how will we know?* 1–3 items. The text states the behaviour change in one line; the measurement goes in its own fields — metric, baseline, target, current. Don't restate the metric in the text, and leave a field empty rather than inventing a number.
Avoid: outputs ("Launch new dashboard").

> ✗ Ship a redesigned onboarding flow.
> ✗ More new admins invite a teammate in their first week (tracked via invites sent within 7 days of signup, currently 22%).
> ✓ More new admins invite a teammate in their first week. — metric: invites sent within 7 days of signup · baseline: 22% · target: 40%

**Open questions.** *What don't we know that could change the direction of more than one spec?* Each item is a real question, answerable by someone or something. When one is answered, the answer and its reason go in its resolution and the question is checked: keep the question as it was, and don't fold the answer into its text.

**Sources.** As above: links only.

---

## Spec

A spec is read by a human deciding whether it's right and by an agent deciding what to build. Write for both: short, specific, unambiguous.

### Overview

**Problem.** *Who has what problem, in what situation, and what does it cost them?*
Budget: 2–4 sentences. Link the evidence rather than retelling it. No solution language.

**Goals.** *What does success look like?* 1–3 items, observable outcomes.
Done when: each could be checked after launch.

**Non-goals.** *What would a reasonable person assume is in scope, but isn't?*
2–5 items. Only list things someone might actually expect: "not building a mobile app" is only useful if someone might have assumed a mobile app. They bind whoever builds this, so don't list something you only mean to defer.

**Research plans.** Links only. No summary.

**Sources.** Links only: workspace documents, or files uploaded to the spec.

**Open questions.** Real, answerable questions that block or shape the build. Good sources are the four risks: will they use it (value), can they use it (usability), can we build it (feasibility), and does it work for the business (viability). Skip any risk that is already answered. An open question stops a build, so don't leave one open that you could settle by asking. Answers go in the resolution, as on an initiative.

**Acceptance criteria.** *How do we verify the build is done?*
Each item is observable and testable by a person or an agent. Use "Given / when / then" when behaviour depends on state. One behaviour per item, with no reasoning attached — the reasoning is a Decision.
Avoid: quality adjectives ("fast", "intuitive") without a threshold.

> ✗ The invite flow should be easy to use.
> ✓ Given an admin with no teammates, when they open Team, they see the invite form without scrolling.

### Solution

**Solution.** *What are we building and how does it work?*
Describe behaviour and flow from the user's side: what they see, what they can do, what happens. Budget: short paragraphs, as long as it needs to be unambiguous and no longer. Leave visual detail to linked artefacts.

**Design principles.** *Which trade-offs will guide decisions not covered here?*
2–4 items, each phrased as "X over Y" so it can settle a disagreement.
Avoid: universal virtues ("simple", "consistent", "accessible"). Those are always true, so they guide nothing.

> ✗ Keep it simple and intuitive.
> ✓ Sensible defaults over upfront configuration.

**Constraints.** *What hard limits come from outside the team?* Technical, legal, time, or platform limits. Facts only, one per item. A constraint is binding on the build, so don't write a preference as one.

**Decisions.** One settled decision per line, with the reason it was settled that way. This is the only place that reasoning goes — don't repeat it in an open question or an acceptance criterion.

**Artefacts.** External links with a label of a few words. No descriptions. Reference material that lives in the workspace is a Source, not an artefact.

**Notes.** Implementation grounding and background: what an agent found in the code, what was built, how it was checked. Not a place for leftover content from other fields.

### Plan

**Tasks.** Each task is a small, verifiable slice, ideally something that can be demonstrated on its own. Start with a verb. One line each — a task is its text and its state, nothing under it. Order them by dependency, and leave the order alone as states change.
Avoid: layer-by-layer tasks ("Build backend", "Build frontend") when a vertical slice is possible.

**Approach.** *How will it be built?* Markdown is allowed here: components touched, data changes, risky parts, and how they'll be de-risked. Reference the codebase by path. Skip anything an engineer or agent would do by default anyway.

---

## Documents

Documents hold the context several specs share — Product knowledge (what's true about the product and the people using it), Standards (the contracts a build has to satisfy), and any section the team adds.

- Before writing a new document, check whether it belongs in one that exists. Two documents on the same subject are worse than one long one.
- A standard is testable: a reader can tell whether a build meets it. Product knowledge is durable context, not news — if it will be wrong next month, it's a signal.
- Anything true of only one spec belongs on that spec, not here.
- The design system is \`DESIGN.md\`. Tokens, type and component rules go there, never into a spec or a document.

---

## Working with the human

- When asked to fill a whole template, draft only the fields you can ground in the input or linked files. In chat, name the fields you left empty in one line.
- When evidence is thin, ask one sharp question rather than inventing a plausible answer.
- When revising, change only the field asked about.
- If the human's draft is long, offer a tightened version. Don't silently rewrite their voice.
`;
